# Generated by Django 4.2.4 on 2024-05-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('softdel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.softdel')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
            bases=('myapp.softdel',),
        ),
        migrations.CreateModel(
            name='Vegitables',
            fields=[
                ('softdel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.softdel')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
            bases=('myapp.softdel',),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('softdel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.softdel')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(default='slug')),
            ],
            bases=('myapp.softdel',),
        ),
    ]
