# Generated by Django 4.2.4 on 2024-05-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='vendor_fruits',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='myapp.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegitables',
            name='vendor_vegitables',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vegitables', to='myapp.vendor'),
            preserve_default=False,
        ),
    ]
