# Generated by Django 4.2.4 on 2024-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fruits_vendor_fruits_vegitables_vendor_vegitables'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='images/image.jpg', upload_to='images'),
        ),
    ]
