# Generated by Django 4.2.4 on 2024-05-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='image/image.jpg', upload_to='image'),
        ),
    ]
